apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app
        image: mlops-demo:3.10-python-production   # Tag will match your build
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
