version: '3'
services:
  api:
    build: .
    ports: 
     - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
  
  prometheus:
    image: prom/prometheus:latest
    volumes: 
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - ./alerts.yml:/etc/prometheus/alerts.yml
     - ./alertmanager.yml:/etc/prometheus/alertmanager.yml
    ports: 
      - "9090:9090"
  
  grafana:
    image: grafana/grafana:10.0.0
    ports: 
     - "3000:3000"