name: PR Activity Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]

jobs:
  initial_validation:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: pytest tests/

  rerun-tests:
    if: github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: pytest tests/
  
  resume-tests: 
    if: github.event.action == 'reopened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pytest tests/
  
  full-test-suite:
    if github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pytest tests/

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cleanup or notificaiton triggered for closed PR ${{ github.event.pull_request.number }}"