name: Automated retrain PR workflow

on:
  workflow_dispatch:

jobs:
  Automated retraining:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r CI-CD_monitoring_testing-practice\feedback-loop\requirements.txttxt
      
      - name: Retrain model
        run: | 
          python CI-CD_monitoring_testing-practice\feedback-loop\train_model.py
      
      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create retrain branch
        run: |
          git checkout -b automated/retrain-$(date + '%y%m%d')
      
      - name: Commit retrained model
        run: |
          git add model.pkl
          git commit -m "Added retrained model on $(date + '%Y-%m-%d')"
      
      - name: Push retrain branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --set-upstream origin HEAD
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: automated/retrain-$(date+'%Y-%m-%d')
          base: main
          title: "Automated Retrain: $(date+'%Y-%m-%d')"
          body: |
            This PR was automatically craeted by a scheduled GIthub Action to retrain the model
          commit-message: "Auomated model retrain"
          token: ${{ secrets.GITHUB_TOKEN }}
