# name: Deploy APploication

# on: 
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Deploy to AWS
#         env:
#           AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
#         run: |
#           aws s3 sync ./build s3://my-bucket