name: Automated Deployment Pipeline
on: 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup @v4
        with:
          python-version: '3.9'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      
      - name: Run tests
        run: |
          python -m pytest tests/ -v
      
      - name: Build application
        run: |
        python setu.py build
      
      - name: Deploy to production
        if github.ref == 'refs/head/main'
        run: |
          echo "Deploying to production"
=
