name: Matrix Strategies for Multi-Environment Testing
on: push

jobs:
  test:
    runs-on: ubuntu-latest  # or ${{ matrix.os }} if you add os to the matrix
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        platform: [cpu, gpu]
        experimental: [false]
        include:
          - python-version: "3.10"
            platform: cpu
            experimental: true
        exclude:
          - python-version: "3.9"
            platform: gpu
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}