name: MLOps Container Matrix Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        base-image: [python]
        deployment-target: [staging, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker image in Minikube
        run: |
          minikube image build -t mlops-demo:${{ matrix.python-version }}-${{ matrix.base-image }}-${{ matrix.deployment-target }} .

      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=${{ matrix.python-version }}-${{ matrix.base-image }}-${{ matrix.deployment-target }}" >> $GITHUB_ENV

      - name: Substitute image tag in manifest
        run: |
          envsubst < deploy/k8s.yaml > deploy/k8s-subst.yaml

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy/k8s-subst.yaml
          kubectl rollout status deployment/ml-app --timeout=180s
          kubectl get pods -o wide
          kubectl describe deployment ml-app