# name: MLOps pipeline with Secrets

# on: 
#   workflow_dispatch:

# jobs:
#   data-preprocessing:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'
      
#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Access Database
#         env:
#           DB_CONNECTION_STRING: ${{ secrets.DATABASE_URL }}
#           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#         run: |
#           python preprocess.data.py

#   model-training:
#     needs: data-preprocessing
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Train model
#         env:
#           MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_URI }}
#           MLFLOW_TRACKING_TOKEN: ${{ secrets.MLFLOW_TOKEN }}

#         run: |
#           python train_model.py
  
#   deploy-to-production:
#     needs: model-training
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Deploy model
#         env:
#           CLOUD_API_KEY: ${{ secrets.PROD_CLOUD_API_KEY }}
#           DEPLOYMENT_TOKEN: ${{ secrets.PROD_DEPLOY_TOKEN }}
        
#         run: |
#           python deploy_model.py