name: PR Opened- Initial model validation

on:
  pull_request:
    types: [opened]

jobs:
  validate_model:
    runs-on: ubuntu-latest
    steps:    
      - name: Run initial model validation tests
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          
        
      - name: Run test
        run: pytest tests/