name: Scheduling Actions

on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '* * * * *'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Message
        run: | 
          echo "Workflow is triggering at $(date)"
          echo "This workflow runs every minute for testing"

