# name: Sequential Workflow
# on: [push]

# jobs:
#   unit-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Run Unit Tests
#         run: npm test
#   integration-test:
#     runs-on: ubuntu-latest
#     needs: unit-test
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Run Integration Tests
#         run: npm run test:integration
      
#   lint:
#     runs-on: ubuntu-latest
#     needs: integration-test
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Run Linting
#         run: npm run lint

        