name: PR Synchronize - Re-run Tests

on:
  pull_request:
    types: [synchronize]

jobs:
  rerun-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Re-run tests on code changes
        uses: actions/checkout@v4

      - name: Run test
        run: |
          pip install pytest
          pytest tests/